services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/var/lib/prometheus
    restart: unless-stopped

  grafana:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - prometheus

  nvitop-exporter:
    build:
      dockerfile: Dockerfile
      context: ..
    command: ["--bind-address", "0.0.0.0", "--port", "5050"]
    pid: host
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  prometheus_storage: {}
  grafana_storage: {}
